In [3]:
print("F1 Race Predictor is ready!")

F1 Race Predictor is ready!

In [4]:
import pandas as pd

races = pd.read_csv("../data/raw/races.csv")

print("Rows:", len(races))
print("Columns:", list(races.columns))

Rows: 1172
Columns: ['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'time', 'url', 'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date', 'quali_time', 'sprint_date', 'sprint_time']

In [5]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [6]:
print("First year:", races["year"].min())
print("Last year:", races["year"].max())
print("Number of seasons:", races["year"].nunique())

First year: 1950
Last year: 2026
Number of seasons: 77

In [7]:
results = pd.read_csv("../data/raw/results.csv")

print("Rows:", len(results))
print("Columns:", list(results.columns))

Rows: 27502
Columns: ['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid', 'position', 'positionText', 'positionOrder', 'points', 'laps', 'time', 'milliseconds', 'fastestLap', 'rank', 'fastestLapTime', 'fastestLapSpeed', 'statusId']

In [8]:
print("Result rows:", len(results))
print("Unique races:", results["raceId"].nunique())
print("Unique drivers:", results["driverId"].nunique())
print("Unique constructors:", results["constructorId"].nunique())

Result rows: 27502
Unique races: 1161
Unique drivers: 865
Unique constructors: 213

In [9]:
qualifying = pd.read_csv("../data/raw/qualifying.csv")

print("Rows:", len(qualifying))
print("Columns:", list(qualifying.columns))

Rows: 11234
Columns: ['qualifyId', 'raceId', 'driverId', 'constructorId', 'number', 'position', 'q1', 'q2', 'q3']

In [10]:
drivers = pd.read_csv("../data/raw/drivers.csv")

print("Rows:", len(drivers))
print("Columns:", list(drivers.columns))

Rows: 865
Columns: ['driverId', 'driverRef', 'number', 'code', 'forename', 'surname', 'dob', 'nationality', 'url']

In [11]:
constructors = pd.read_csv("../data/raw/constructors.csv")

print("Rows:", len(constructors))
print("Columns:", list(constructors.columns))

Rows: 214
Columns: ['constructorId', 'constructorRef', 'name', 'nationality', 'url']

In [12]:
circuits = pd.read_csv("../data/raw/circuits.csv")

print("Rows:", len(circuits))
print("Columns:", list(circuits.columns))

Rows: 78
Columns: ['circuitId', 'circuitRef', 'name', 'location', 'country', 'lat', 'lng', 'alt', 'url']

In [13]:
results.isnull().sum()

resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

In [14]:
qualifying.isnull().sum()

qualifyId        0
raceId           0
driverId         0
constructorId    0
number           0
position         0
q1               0
q2               0
q3               0
dtype: int64

In [15]:
drivers.isnull().sum()

driverId       0
driverRef      0
number         0
code           0
forename       0
surname        0
dob            0
nationality    0
url            0
dtype: int64

In [16]:
constructors.isnull().sum()

constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64

In [17]:
circuits.isnull().sum()

circuitId     0
circuitRef    0
name          0
location      0
country       0
lat           0
lng           0
alt           0
url           0
dtype: int64

In [18]:
races = pd.read_csv("../data/raw/races.csv")

In [19]:
races = pd.read_csv("../data/raw/races.csv")

In [20]:
print("Races:", len(races))
print("Results:", len(results))
print("Qualifying:", len(qualifying))
print("Drivers:", len(drivers))
print("Constructors:", len(constructors))
print("Circuits:", len(circuits))

Races: 1172
Results: 27502
Qualifying: 11234
Drivers: 865
Constructors: 214
Circuits: 78

In [21]:
print("Races:", races.shape)
print("Results:", results.shape)
print("Qualifying:", qualifying.shape)
print("Drivers:", drivers.shape)
print("Constructors:", constructors.shape)
print("Circuits:", circuits.shape)

Races: (1172, 18)
Results: (27502, 18)
Qualifying: (11234, 9)
Drivers: (865, 9)
Constructors: (214, 5)
Circuits: (78, 9)

In [22]:
races["year"].value_counts().sort_index()

year
1950     7
1951     8
1952     8
1953     9
1954     9
        ..
2022    22
2023    22
2024    24
2025    24
2026    23
Name: count, Length: 77, dtype: int64

In [23]:
results["driverId"].value_counts().head(10)

driverId
4      440
1      392
8      352
22     326
18     309
30     308
20     300
815    295
13     271
807    266
Name: count, dtype: int64

In [24]:
top_drivers = results["driverId"].value_counts().head(10)

top_drivers = top_drivers.reset_index()
top_drivers.columns = ["driverId", "race_results"]

top_drivers.merge(
    drivers[["driverId", "forename", "surname"]],
    on="driverId"
)

   driverId  race_results   forename      surname
0         4           440   Fernando       Alonso
1         1           392      Lewis     Hamilton
2         8           352       Kimi    Räikkönen
3        22           326     Rubens  Barrichello
4        18           309     Jenson       Button
5        30           308    Michael   Schumacher
6        20           300  Sebastian       Vettel
7       815           295     Sergio        Pérez
8        13           271     Felipe        Massa
9       807           266       Nico   Hülkenberg

In [25]:

results["position"].value_counts().head(15)

position
\N    10953
3      1171
4      1171
2      1169
5      1167
1      1164
6      1160
7      1140
8      1112
9      1074
10     1014
11      937
12      836
13      749
14      641
Name: count, dtype: int64

In [26]:
results["grid"].value_counts().head(15)

grid
0     1638
1     1171
7     1170
5     1167
11    1167
9     1167
4     1167
3     1165
10    1165
8     1164
12    1162
13    1160
2     1160
6     1160
14    1155
Name: count, dtype: int64

In [27]:
podium = results["position"].isin(["1", "2", "3"])

print("Podium finishes:", podium.sum())
print("Non-podium results:", (~podium).sum())

Podium finishes: 3504
Non-podium results: 23998

In [28]:
results_with_races = results.merge(
    races[["raceId", "year"]],
    on="raceId",
    how="left"
)

results_with_races["podium"] = results_with_races["position"].isin(["1", "2", "3"])

podium_by_year = results_with_races.groupby("year")["podium"].sum()

podium_by_year.head(10)

year
1950    22
1951    28
1952    24
1953    29
1954    29
1955    27
1956    29
1957    25
1958    33
1959    27
Name: podium, dtype: int64

In [29]:
podium_by_driver = (
    results[results["position"].isin(["1", "2", "3"])]
    .groupby("driverId")
    .size()
    .reset_index(name="podium_finishes")
)

podium_by_driver = podium_by_driver.merge(
    drivers[["driverId", "forename", "surname"]],
    on="driverId"
)

podium_by_driver.sort_values(
    "podium_finishes",
    ascending=False
).head(10)

     driverId  podium_finishes   forename      surname
0           1              207      Lewis     Hamilton
20         30              155    Michael   Schumacher
207       830              131        Max   Verstappen
15         20              122  Sebastian       Vettel
3           4              106   Fernando       Alonso
47        117              106      Alain        Prost
5           8              103       Kimi    Räikkönen
42        102               80     Ayrton        Senna
17         22               68     Rubens  Barrichello
204       822               67   Valtteri       Bottas

In [30]:
podium_by_constructor = (
    results[results["position"].isin(["1", "2", "3"])]
    .groupby("constructorId")
    .size()
    .reset_index(name="podium_finishes")
)

podium_by_constructor = podium_by_constructor.merge(
    constructors[["constructorId", "name"]],
    on="constructorId"
)

podium_by_constructor.sort_values(
    "podium_finishes",
    ascending=False
).head(10)

    constructorId  podium_finishes        name
5               6              857     Ferrari
0               1              548     McLaren
53            131              326    Mercedes
2               3              315    Williams
7               9              301    Red Bull
23             32              114  Team Lotus
3               4              103     Renault
16             22              102    Benetton
25             34               78     Brabham
19             25               77     Tyrrell

In [31]:
qualifying_results = qualifying.merge(
    results[["raceId", "driverId", "position"]],
    on=["raceId", "driverId"],
    how="inner"
)

print("Records:", len(qualifying_results))
print("Columns:", list(qualifying_results.columns))

Records: 11233
Columns: ['qualifyId', 'raceId', 'driverId', 'constructorId', 'number', 'position_x', 'q1', 'q2', 'q3', 'position_y']

In [32]:
qualifying_results[["position_x", "position_y"]].head(10)

   position_x position_y
0           1          1
1           2         \N
2           3          5
3           4         \N
4           5          2
5           6         \N
6           7          3
7           8         \N
8           9         \N
9          10         \N

In [33]:
qr = qualifying_results.copy()

qr["qualifying_position"] = pd.to_numeric(qr["position_x"], errors="coerce")
qr["finish_position"] = pd.to_numeric(qr["position_y"], errors="coerce")

qr = qr.dropna(subset=["qualifying_position", "finish_position"])

print(
    "Correlation:",
    qr["qualifying_position"].corr(qr["finish_position"])
)

Correlation: 0.7320076934123602

In [34]:
grid_results = results.copy()

grid_results["grid_position"] = pd.to_numeric(
    grid_results["grid"],
    errors="coerce"
)

grid_results["finish_position"] = pd.to_numeric(
    grid_results["position"],
    errors="coerce"
)

grid_results = grid_results.dropna(
    subset=["grid_position", "finish_position"]
)

print(
    "Correlation:",
    grid_results["grid_position"].corr(
        grid_results["finish_position"]
    )
)

Correlation: 0.6321798688549147

In [35]:
results["points"].describe()

count    27502.000000
mean         2.066142
std          4.473378
min          0.000000
25%          0.000000
50%          0.000000
75%          2.000000
max         50.000000
Name: points, dtype: float64

In [36]:
results["fastestLapSpeed"].describe()

count     27502
unique     7725
top          \N
freq      19250
Name: fastestLapSpeed, dtype: object

In [37]:
qualifying[["q1", "q2", "q3"]].head(10)

         q1        q2        q3
0  1:26.572  1:25.187  1:26.714
1  1:26.103  1:25.315  1:26.869
2  1:25.664  1:25.452  1:27.079
3  1:25.994  1:25.691  1:27.178
4  1:25.960  1:25.518  1:27.236
5  1:26.427  1:26.101  1:28.527
6  1:26.295  1:26.059  1:28.687
7  1:26.381  1:26.063  1:29.041
8  1:26.919  1:26.164  1:29.593
9  1:26.702  1:25.842        \N

In [38]:
print("Total qualifying records:", len(qualifying))
print("Q3 available:", (qualifying["q3"] != r"\N").sum())
print("Q3 missing:", (qualifying["q3"] == r"\N").sum())

Total qualifying records: 11234
Q3 available: 3981
Q3 missing: 7253

In [39]:
print("Q1 missing:", (qualifying["q1"] == r"\N").sum())
print("Q2 missing:", (qualifying["q2"] == r"\N").sum())
print("Q3 missing:", (qualifying["q3"] == r"\N").sum())

Q1 missing: 164
Q2 missing: 4842
Q3 missing: 7253

In [40]:
unique_podium_drivers = results[
    results["position"].isin(["1", "2", "3"])
]["driverId"].nunique()

print("Drivers with at least one podium:", unique_podium_drivers)

Drivers with at least one podium: 219

In [41]:
podium_percentage = (
    results["position"].isin(["1", "2", "3"]).mean() * 100
)

print(f"Overall podium percentage: {podium_percentage:.2f}%")

Overall podium percentage: 12.74%

In [42]:
driver_race_counts = (
    results.groupby("driverId")
    .size()
    .reset_index(name="race_count")
)

print(driver_race_counts["race_count"].describe())

count    865.000000
mean      31.794220
std       57.925852
min        1.000000
25%        2.000000
50%        7.000000
75%       32.000000
max      440.000000
Name: race_count, dtype: float64

In [43]:
races[["year", "name"]].tail(10)

      year                            name
1162  2026              Spanish Grand Prix
1163  2026           Azerbaijan Grand Prix
1164  2026  Bahrain Grand Prix in Malaysia
1165  2026            Singapore Grand Prix
1166  2026        United States Grand Prix
1167  2026          Mexico City Grand Prix
1168  2026            Brazilian Grand Prix
1169  2026            Las Vegas Grand Prix
1170  2026                Qatar Grand Prix
1171  2026            Abu Dhabi Grand Prix

In [44]:
races.groupby("year").size().tail(10)

year
2017    20
2018    21
2019    21
2020    17
2021    22
2022    22
2023    22
2024    24
2025    24
2026    23
dtype: int64

In [45]:

print("Latest race date:", races["date"].max())

Latest race date: 2026-12-06

In [46]:
today = pd.Timestamp.today().normalize()

completed_races = races[
    pd.to_datetime(races["date"]) <= today
]

print("Today's date:", today.date())
print("Completed races:", len(completed_races))
print("Latest completed race:", completed_races["date"].max())

Today's date: 2026-08-28
Completed races: 1161
Latest completed race: 2026-08-23

In [47]:
completed_races = races[
    pd.to_datetime(races["date"]) <= today
].copy()

print("Completed races:", len(completed_races))
print("Future races excluded:", len(races) - len(completed_races))

Completed races: 1161
Future races excluded: 11

In [48]:
completed_results = results.merge(
    completed_races[["raceId", "year", "date", "name", "circuitId"]],
    on="raceId",
    how="inner"
)

print("Completed result records:", len(completed_results))
print("Races represented:", completed_results["raceId"].nunique())

Completed result records: 27502
Races represented: 1161

In [49]:
completed_results["podium"] = (
    completed_results["position"].isin(["1", "2", "3"]).astype(int)
)

print(completed_results["podium"].value_counts())

podium
0    23998
1     3504
Name: count, dtype: int64

In [50]:

print(completed_results["podium"].dtype)
print(completed_results[["driverId", "constructorId", "grid", "podium"]].head())

int64
   driverId  constructorId grid  podium
0         1              1    1       1
1         2              2    5       1
2         3              3    7       1
3         4              4   11       0
4         5              1    3       0

In [51]:
recent_constructor_podiums = (
    completed_results
    .sort_values(["date", "raceId"])
    .groupby("constructorId")["podium"]
    .sum()
    .reset_index(name="total_podiums")
)

recent_constructor_podiums.sort_values(
    "total_podiums",
    ascending=False
).head(10)

     constructorId  total_podiums
5                6            857
0                1            548
128            131            326
2                3            315
8                9            301
31              32            114
3                4            103
21              22            102
33              34             78
24              25             77

In [52]:
completed_results = completed_results.sort_values(
    ["date", "raceId", "driverId"]
).reset_index(drop=True)

print(completed_results[["date", "raceId", "driverId", "podium"]].head(10))

         date  raceId  driverId  podium
0  1950-05-13     833       579       0
1  1950-05-13     833       589       0
2  1950-05-13     833       619       0
3  1950-05-13     833       627       0
4  1950-05-13     833       640       0
5  1950-05-13     833       642       1
6  1950-05-13     833       660       0
7  1950-05-13     833       661       0
8  1950-05-13     833       666       0
9  1950-05-13     833       669       0

In [53]:
completed_results["previous_finish"] = (
    completed_results
    .groupby("driverId")["position"]
    .shift(1)
)

print(
    completed_results[
        ["driverId", "date", "position", "previous_finish"]
    ].head(20)
)

    driverId        date position previous_finish
0        579  1950-05-13       \N             NaN
1        589  1950-05-13       \N             NaN
2        619  1950-05-13        6             NaN
3        627  1950-05-13        5             NaN
4        640  1950-05-13       \N             NaN
5        642  1950-05-13        1             NaN
6        660  1950-05-13       11             NaN
7        661  1950-05-13       \N             NaN
8        666  1950-05-13       \N             NaN
9        669  1950-05-13       \N             NaN
10       686  1950-05-13        3             NaN
11       704  1950-05-13        4             NaN
12       741  1950-05-13        8             NaN
13       747  1950-05-13       \N             NaN
14       776  1950-05-13       \N             NaN
15       778  1950-05-13       10             NaN
16       784  1950-05-13        9             NaN
17       785  1950-05-13       \N             NaN
18       786  1950-05-13        2             NaN
19       787  1950-05-13        7             NaN

In [54]:
print("Total records:", len(completed_results))
print("With previous result:", completed_results["previous_finish"].notna().sum())
print("Without previous result:", completed_results["previous_finish"].isna().sum())

Total records: 27502
With previous result: 26637
Without previous result: 865

In [55]:
completed_results["previous_finish_num"] = pd.to_numeric(
    completed_results["previous_finish"],
    errors="coerce"
)

print(
    completed_results[
        ["previous_finish", "previous_finish_num"]
    ].head(20)
)

   previous_finish  previous_finish_num
0              NaN                  NaN
1              NaN                  NaN
2              NaN                  NaN
3              NaN                  NaN
4              NaN                  NaN
5              NaN                  NaN
6              NaN                  NaN
7              NaN                  NaN
8              NaN                  NaN
9              NaN                  NaN
10             NaN                  NaN
11             NaN                  NaN
12             NaN                  NaN
13             NaN                  NaN
14             NaN                  NaN
15             NaN                  NaN
16             NaN                  NaN
17             NaN                  NaN
18             NaN                  NaN
19             NaN                  NaN

In [56]:
print("Numeric previous finishes:",
      completed_results["previous_finish_num"].notna().sum())

print(
    completed_results[
        completed_results["previous_finish_num"].notna()
    ][["driverId", "position", "previous_finish_num"]].head(10)
)

Numeric previous finishes: 16196
    driverId position  previous_finish_num
28       619        6                  6.0
30       627       \N                  5.0
33       642       \N                  1.0
35       660        7                 11.0
38       741       \N                  8.0
40       786       \N                  2.0
41       787       \N                  7.0
80       579       \N                  1.0
81       589        9                  3.0
86       647       \N                  2.0

In [57]:
completed_results[
    completed_results["driverId"] == 1
][
    ["date", "raceId", "position", "previous_finish_num"]
].head(10)

             date  raceId position  previous_finish_num
19241  2007-03-18      36        3                  NaN
19263  2007-04-08      37        2                  3.0
19285  2007-04-15      38        2                  2.0
19307  2007-05-13      39        2                  2.0
19329  2007-05-27      40        2                  2.0
19351  2007-06-10      41        1                  2.0
19373  2007-06-17      42        1                  1.0
19395  2007-07-01      43        3                  1.0
19417  2007-07-08      44        3                  3.0
19439  2007-07-22      45        9                  3.0

In [58]:
completed_results["previous_podium"] = (
    completed_results
    .groupby("driverId")["podium"]
    .shift(1)
)

print(
    completed_results[
        ["driverId", "position", "podium", "previous_podium"]
    ].head(30)
)

    driverId position  podium  previous_podium
0        579       \N       0              NaN
1        589       \N       0              NaN
2        619        6       0              NaN
3        627        5       0              NaN
4        640       \N       0              NaN
5        642        1       1              NaN
6        660       11       0              NaN
7        661       \N       0              NaN
8        666       \N       0              NaN
9        669       \N       0              NaN
10       686        3       1              NaN
11       704        4       0              NaN
12       741        8       0              NaN
13       747       \N       0              NaN
14       776       \N       0              NaN
15       778       10       0              NaN
16       784        9       0              NaN
17       785       \N       0              NaN
18       786        2       1              NaN
19       787        7       0              NaN
20       788       10       0              NaN
21       789       \N       0              NaN
22       790       \N       0              NaN
23       427       \N       0              NaN
24       498       \N       0              NaN
25       501       \N       0              NaN
26       579        1       1              0.0
27       589        3       1              0.0
28       619        6       0              0.0
29       626       \N       0              NaN

In [59]:
print(
    "Previous podium available:",
    completed_results["previous_podium"].notna().sum()
)

print(
    "Previous podium missing:",
    completed_results["previous_podium"].isna().sum()
)

Previous podium available: 26637
Previous podium missing: 865

In [60]:
completed_results["previous_points"] = (
    completed_results
    .groupby("driverId")["points"]
    .shift(1)
)

print(
    completed_results[
        ["driverId", "points", "previous_points"]
    ].head(30)
)

    driverId  points  previous_points
0        579     0.0              NaN
1        589     0.0              NaN
2        619     0.0              NaN
3        627     2.0              NaN
4        640     0.0              NaN
5        642     9.0              NaN
6        660     0.0              NaN
7        661     0.0              NaN
8        666     0.0              NaN
9        669     0.0              NaN
10       686     4.0              NaN
11       704     3.0              NaN
12       741     0.0              NaN
13       747     0.0              NaN
14       776     0.0              NaN
15       778     0.0              NaN
16       784     0.0              NaN
17       785     0.0              NaN
18       786     6.0              NaN
19       787     0.0              NaN
20       788     0.0              NaN
21       789     0.0              NaN
22       790     0.0              NaN
23       427     0.0              NaN
24       498     0.0              NaN
25       501     0.0              NaN
26       579     9.0              0.0
27       589     4.0              0.0
28       619     0.0              0.0
29       626     0.0              NaN

In [61]:
print(
    "Previous points available:",
    completed_results["previous_points"].notna().sum()
)

print(
    "Previous points missing:",
    completed_results["previous_points"].isna().sum()
)

Previous points available: 26637
Previous points missing: 865

In [62]:
print(
    completed_results[
        [
            "driverId",
            "date",
            "podium",
            "previous_finish_num",
            "previous_podium",
            "previous_points"
        ]
    ].head(20)
)

    driverId        date  podium  previous_finish_num  previous_podium  \
0        579  1950-05-13       0                  NaN              NaN
1        589  1950-05-13       0                  NaN              NaN
2        619  1950-05-13       0                  NaN              NaN
3        627  1950-05-13       0                  NaN              NaN
4        640  1950-05-13       0                  NaN              NaN
5        642  1950-05-13       1                  NaN              NaN
6        660  1950-05-13       0                  NaN              NaN
7        661  1950-05-13       0                  NaN              NaN
8        666  1950-05-13       0                  NaN              NaN
9        669  1950-05-13       0                  NaN              NaN
10       686  1950-05-13       1                  NaN              NaN
11       704  1950-05-13       0                  NaN              NaN
12       741  1950-05-13       0                  NaN              NaN
13       747  1950-05-13       0                  NaN              NaN
14       776  1950-05-13       0                  NaN              NaN
15       778  1950-05-13       0                  NaN              NaN
16       784  1950-05-13       0                  NaN              NaN
17       785  1950-05-13       0                  NaN              NaN
18       786  1950-05-13       1                  NaN              NaN
19       787  1950-05-13       0                  NaN              NaN

    previous_points
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
5               NaN
6               NaN
7               NaN
8               NaN
9               NaN
10              NaN
11              NaN
12              NaN
13              NaN
14              NaN
15              NaN
16              NaN
17              NaN
18              NaN
19              NaN

In [63]:
print("Rows:", completed_results.shape[0])
print("Columns:", completed_results.shape[1])
print("\nColumn names:")
print(completed_results.columns.tolist())

Rows: 27502
Columns: 27

Column names:
['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid', 'position', 'positionText', 'positionOrder', 'points', 'laps', 'time', 'milliseconds', 'fastestLap', 'rank', 'fastestLapTime', 'fastestLapSpeed', 'statusId', 'year', 'date', 'name', 'circuitId', 'podium', 'previous_finish', 'previous_finish_num', 'previous_podium', 'previous_points']

In [64]:
completed_results["recent_5_podiums"] = (
    completed_results
    .groupby("driverId")["podium"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).sum())
)

print(
    completed_results[
        [
            "driverId",
            "date",
            "podium",
            "previous_podium",
            "recent_5_podiums"
        ]
    ].head(30)
)

    driverId        date  podium  previous_podium  recent_5_podiums
0        579  1950-05-13       0              NaN               NaN
1        589  1950-05-13       0              NaN               NaN
2        619  1950-05-13       0              NaN               NaN
3        627  1950-05-13       0              NaN               NaN
4        640  1950-05-13       0              NaN               NaN
5        642  1950-05-13       1              NaN               NaN
6        660  1950-05-13       0              NaN               NaN
7        661  1950-05-13       0              NaN               NaN
8        666  1950-05-13       0              NaN               NaN
9        669  1950-05-13       0              NaN               NaN
10       686  1950-05-13       1              NaN               NaN
11       704  1950-05-13       0              NaN               NaN
12       741  1950-05-13       0              NaN               NaN
13       747  1950-05-13       0              NaN               NaN
14       776  1950-05-13       0              NaN               NaN
15       778  1950-05-13       0              NaN               NaN
16       784  1950-05-13       0              NaN               NaN
17       785  1950-05-13       0              NaN               NaN
18       786  1950-05-13       1              NaN               NaN
19       787  1950-05-13       0              NaN               NaN
20       788  1950-05-13       0              NaN               NaN
21       789  1950-05-13       0              NaN               NaN
22       790  1950-05-13       0              NaN               NaN
23       427  1950-05-21       0              NaN               NaN
24       498  1950-05-21       0              NaN               NaN
25       501  1950-05-21       0              NaN               NaN
26       579  1950-05-21       1              0.0               0.0
27       589  1950-05-21       1              0.0               0.0
28       619  1950-05-21       0              0.0               0.0
29       626  1950-05-21       0              NaN               NaN

In [65]:
print(
    "Recent 5 podiums available:",
    completed_results["recent_5_podiums"].notna().sum()
)

print(
    "Recent 5 podiums missing:",
    completed_results["recent_5_podiums"].isna().sum()
)

Recent 5 podiums available: 26637
Recent 5 podiums missing: 865

In [66]:
completed_results["recent_5_points"] = (
    completed_results
    .groupby("driverId")["points"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).sum())
)

print(
    completed_results[
        [
            "driverId",
            "date",
            "points",
            "previous_points",
            "recent_5_points"
        ]
    ].head(30)
)

    driverId        date  points  previous_points  recent_5_points
0        579  1950-05-13     0.0              NaN              NaN
1        589  1950-05-13     0.0              NaN              NaN
2        619  1950-05-13     0.0              NaN              NaN
3        627  1950-05-13     2.0              NaN              NaN
4        640  1950-05-13     0.0              NaN              NaN
5        642  1950-05-13     9.0              NaN              NaN
6        660  1950-05-13     0.0              NaN              NaN
7        661  1950-05-13     0.0              NaN              NaN
8        666  1950-05-13     0.0              NaN              NaN
9        669  1950-05-13     0.0              NaN              NaN
10       686  1950-05-13     4.0              NaN              NaN
11       704  1950-05-13     3.0              NaN              NaN
12       741  1950-05-13     0.0              NaN              NaN
13       747  1950-05-13     0.0              NaN              NaN
14       776  1950-05-13     0.0              NaN              NaN
15       778  1950-05-13     0.0              NaN              NaN
16       784  1950-05-13     0.0              NaN              NaN
17       785  1950-05-13     0.0              NaN              NaN
18       786  1950-05-13     6.0              NaN              NaN
19       787  1950-05-13     0.0              NaN              NaN
20       788  1950-05-13     0.0              NaN              NaN
21       789  1950-05-13     0.0              NaN              NaN
22       790  1950-05-13     0.0              NaN              NaN
23       427  1950-05-21     0.0              NaN              NaN
24       498  1950-05-21     0.0              NaN              NaN
25       501  1950-05-21     0.0              NaN              NaN
26       579  1950-05-21     9.0              0.0              0.0
27       589  1950-05-21     4.0              0.0              0.0
28       619  1950-05-21     0.0              0.0              0.0
29       626  1950-05-21     0.0              NaN              NaN

In [67]:
print(completed_results["recent_5_points"].describe())

count    26637.000000
mean        10.467878
std         18.490890
min          0.000000
25%          0.000000
50%          3.000000
75%         12.000000
max        143.000000
Name: recent_5_points, dtype: float64

In [68]:
completed_results["constructor_recent_5_podiums"] = (
    completed_results
    .groupby("constructorId")["podium"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).sum())
)

print(
    completed_results[
        [
            "constructorId",
            "date",
            "podium",
            "constructor_recent_5_podiums"
        ]
    ].head(30)
)

    constructorId        date  podium  constructor_recent_5_podiums
0              51  1950-05-13       0                           NaN
1             105  1950-05-13       0                           NaN
2             151  1950-05-13       0                           NaN
3             154  1950-05-13       0                           NaN
4             105  1950-05-13       0                           0.0
5              51  1950-05-13       1                           0.0
6             154  1950-05-13       0                           0.0
7             151  1950-05-13       0                           0.0
8             151  1950-05-13       0                           0.0
9             105  1950-05-13       0                           0.0
10             51  1950-05-13       1                           1.0
11            154  1950-05-13       0                           0.0
12            154  1950-05-13       0                           0.0
13            105  1950-05-13       0                           0.0
14            126  1950-05-13       0                           NaN
15            105  1950-05-13       0                           0.0
16            105  1950-05-13       0                           0.0
17            126  1950-05-13       0                           0.0
18             51  1950-05-13       1                           2.0
19            151  1950-05-13       0                           0.0
20            105  1950-05-13       0                           0.0
21            154  1950-05-13       0                           0.0
22            151  1950-05-13       0                           0.0
23            141  1950-05-21       0                           NaN
24            105  1950-05-21       0                           0.0
25             87  1950-05-21       0                           NaN
26             51  1950-05-21       1                           3.0
27            105  1950-05-21       1                           0.0
28            151  1950-05-21       0                           0.0
29            141  1950-05-21       0                           0.0

In [69]:
print(completed_results["constructor_recent_5_podiums"].describe())

count    27289.000000
mean         0.639745
std          1.089268
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          5.000000
Name: constructor_recent_5_podiums, dtype: float64

In [70]:
completed_results["constructor_recent_5_points"] = (
    completed_results
    .groupby("constructorId")["points"]
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).sum())
)

print(
    completed_results[
        [
            "constructorId",
            "date",
            "points",
            "constructor_recent_5_points"
        ]
    ].head(30)
)

    constructorId        date  points  constructor_recent_5_points
0              51  1950-05-13     0.0                          NaN
1             105  1950-05-13     0.0                          NaN
2             151  1950-05-13     0.0                          NaN
3             154  1950-05-13     2.0                          NaN
4             105  1950-05-13     0.0                          0.0
5              51  1950-05-13     9.0                          0.0
6             154  1950-05-13     0.0                          2.0
7             151  1950-05-13     0.0                          0.0
8             151  1950-05-13     0.0                          0.0
9             105  1950-05-13     0.0                          0.0
10             51  1950-05-13     4.0                          9.0
11            154  1950-05-13     3.0                          2.0
12            154  1950-05-13     0.0                          5.0
13            105  1950-05-13     0.0                          0.0
14            126  1950-05-13     0.0                          NaN
15            105  1950-05-13     0.0                          0.0
16            105  1950-05-13     0.0                          0.0
17            126  1950-05-13     0.0                          0.0
18             51  1950-05-13     6.0                         13.0
19            151  1950-05-13     0.0                          0.0
20            105  1950-05-13     0.0                          0.0
21            154  1950-05-13     0.0                          5.0
22            151  1950-05-13     0.0                          0.0
23            141  1950-05-21     0.0                          NaN
24            105  1950-05-21     0.0                          0.0
25             87  1950-05-21     0.0                          NaN
26             51  1950-05-21     9.0                         19.0
27            105  1950-05-21     4.0                          0.0
28            151  1950-05-21     0.0                          0.0
29            141  1950-05-21     0.0                          0.0

In [71]:
print(completed_results["constructor_recent_5_points"].describe())

count    27289.000000
mean        10.355757
std         17.828097
min          0.000000
25%          0.000000
50%          3.000000
75%         12.000000
max        136.000000
Name: constructor_recent_5_points, dtype: float64

In [72]:
qualifying_features = qualifying[
    ["raceId", "driverId", "position"]
].copy()

qualifying_features = qualifying_features.rename(
    columns={"position": "qualifying_position"}
)

qualifying_features["qualifying_position"] = pd.to_numeric(
    qualifying_features["qualifying_position"],
    errors="coerce"
)

print(qualifying_features.head(10))

   raceId  driverId  qualifying_position
0      18         1                    1
1      18         9                    2
2      18         5                    3
3      18        13                    4
4      18         2                    5
5      18        15                    6
6      18         3                    7
7      18        14                    8
8      18        10                    9
9      18        20                   10

In [73]:
# Remove any old qualifying position column
completed_results = completed_results.drop(
    columns=["qualifying_position"],
    errors="ignore"
)

# Merge qualifying position again
completed_results = completed_results.merge(
    qualifying_features,
    on=["raceId", "driverId"],
    how="left"
)

print(
    completed_results[
        ["raceId", "driverId", "qualifying_position", "podium"]
    ].head(20)
)

    raceId  driverId  qualifying_position  podium
0      833       579                  NaN       0
1      833       589                  NaN       0
2      833       619                  NaN       0
3      833       627                  NaN       0
4      833       640                  NaN       0
5      833       642                  NaN       1
6      833       660                  NaN       0
7      833       661                  NaN       0
8      833       666                  NaN       0
9      833       669                  NaN       0
10     833       686                  NaN       1
11     833       704                  NaN       0
12     833       741                  NaN       0
13     833       747                  NaN       0
14     833       776                  NaN       0
15     833       778                  NaN       0
16     833       784                  NaN       0
17     833       785                  NaN       0
18     833       786                  NaN       1
19     833       787                  NaN       0

In [74]:
print(
    [c for c in completed_results.columns
     if "qualifying" in c.lower()]
)

['qualifying_position']

In [75]:
completed_results = completed_results.drop(
    columns=[
        "qualifying_position_x",
        "qualifying_position_y",
        "qualifying_position"
    ],
    errors="ignore"
)

completed_results = completed_results.merge(
    qualifying_features,
    on=["raceId", "driverId"],
    how="left"
)

print(
    completed_results[
        ["raceId", "driverId", "qualifying_position", "podium"]
    ].head(20)
)

    raceId  driverId  qualifying_position  podium
0      833       579                  NaN       0
1      833       589                  NaN       0
2      833       619                  NaN       0
3      833       627                  NaN       0
4      833       640                  NaN       0
5      833       642                  NaN       1
6      833       660                  NaN       0
7      833       661                  NaN       0
8      833       666                  NaN       0
9      833       669                  NaN       0
10     833       686                  NaN       1
11     833       704                  NaN       0
12     833       741                  NaN       0
13     833       747                  NaN       0
14     833       776                  NaN       0
15     833       778                  NaN       0
16     833       784                  NaN       0
17     833       785                  NaN       0
18     833       786                  NaN       1
19     833       787                  NaN       0

In [76]:
print("Total results:", len(completed_results))
print(
    "Qualifying available:",
    completed_results["qualifying_position"].notna().sum()
)
print(
    "Qualifying missing:",
    completed_results["qualifying_position"].isna().sum()
)

Total results: 27502
Qualifying available: 11233
Qualifying missing: 16269

In [77]:
qualifying_podium = completed_results.dropna(
    subset=["qualifying_position"]
)

print(
    qualifying_podium.groupby("qualifying_position")["podium"]
    .mean()
    .head(10)
)

qualifying_position
1.0     0.764151
2.0     0.628302
3.0     0.503774
4.0     0.349057
5.0     0.235849
6.0     0.145283
7.0     0.094340
8.0     0.052830
9.0     0.041509
10.0    0.037736
Name: podium, dtype: float64

In [78]:
grid_podium = completed_results.copy()

grid_podium["grid_position"] = pd.to_numeric(
    grid_podium["grid"],
    errors="coerce"
)

grid_podium = grid_podium.dropna(
    subset=["grid_position"]
)

print(
    grid_podium.groupby("grid_position")["podium"]
    .mean()
    .head(10)
)

grid_position
0.0    0.000000
1.0    0.640478
2.0    0.562931
3.0    0.464378
4.0    0.344473
5.0    0.247644
6.0    0.181897
7.0    0.128205
8.0    0.096220
9.0    0.081405
Name: podium, dtype: float64

In [79]:
previous_finish_podium = completed_results.dropna(
    subset=["previous_finish_num"]
)

print(
    previous_finish_podium.groupby("previous_finish_num")["podium"]
    .mean()
    .head(10)
)

previous_finish_num
1.0     0.545298
2.0     0.437069
3.0     0.322747
4.0     0.256255
5.0     0.190641
6.0     0.121823
7.0     0.089366
8.0     0.087076
9.0     0.054286
10.0    0.040161
Name: podium, dtype: float64

In [80]:
recent_form_podium = completed_results.dropna(
    subset=["recent_5_podiums"]
)

print(
    recent_form_podium
    .groupby("recent_5_podiums")["podium"]
    .mean()
)

recent_5_podiums
0.0    0.036345
1.0    0.191136
2.0    0.362529
3.0    0.455172
4.0    0.586041
5.0    0.654485
Name: podium, dtype: float64

In [81]:
recent_points_podium = completed_results.dropna(
    subset=["recent_5_points"]
)

print(
    recent_points_podium
    .groupby("recent_5_points")["podium"]
    .mean()
    .head(15)
)

recent_5_points
0.00    0.019126
0.50    0.000000
1.00    0.032974
1.33    0.000000
1.50    0.058824
2.00    0.047297
2.50    0.666667
3.00    0.081148
3.33    0.000000
3.50    0.000000
4.00    0.071245
4.14    0.000000
4.50    0.000000
5.00    0.090164
5.33    1.000000
Name: podium, dtype: float64

In [82]:
constructor_form_podium = completed_results.dropna(
    subset=["constructor_recent_5_podiums"]
)

print(
    constructor_form_podium
    .groupby("constructor_recent_5_podiums")["podium"]
    .mean()
)

constructor_recent_5_podiums
0.0    0.040616
1.0    0.190136
2.0    0.327909
3.0    0.436658
4.0    0.524854
5.0    0.625616
Name: podium, dtype: float64

In [83]:
constructor_points_form = completed_results.dropna(
    subset=["constructor_recent_5_points"]
)

print(
    constructor_points_form
    .groupby("constructor_recent_5_points")["podium"]
    .mean()
    .head(15)
)

constructor_recent_5_points
0.00    0.021492
0.50    0.000000
1.00    0.035910
1.50    0.172414
2.00    0.054749
2.50    0.000000
3.00    0.080572
3.33    1.000000
3.50    0.076923
4.00    0.080589
4.14    0.000000
4.50    0.230769
5.00    0.088023
5.33    1.000000
5.50    0.500000
Name: podium, dtype: float64

In [84]:
feature_columns = [
    "grid",
    "qualifying_position",
    "previous_finish_num",
    "previous_podium",
    "previous_points",
    "recent_5_podiums",
    "recent_5_points",
    "constructor_recent_5_podiums",
    "constructor_recent_5_points",
]

print("Number of features:", len(feature_columns))
print("\nFeatures:")
for feature in feature_columns:
    print("-", feature)

Number of features: 9

Features:
- grid
- qualifying_position
- previous_finish_num
- previous_podium
- previous_points
- recent_5_podiums
- recent_5_points
- constructor_recent_5_podiums
- constructor_recent_5_points

In [85]:
print("completed_results" in globals())
print("feature_columns" in globals())

True
True

In [86]:

print(
    completed_results[feature_columns].isna().sum()
)

grid                                0
qualifying_position             16269
previous_finish_num             11306
previous_podium                   865
previous_points                   865
recent_5_podiums                  865
recent_5_points                   865
constructor_recent_5_podiums      213
constructor_recent_5_points       213
dtype: int64

In [87]:
missing_percentage = (
    completed_results[feature_columns]
    .isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

print(missing_percentage)

qualifying_position             59.155698
previous_finish_num             41.109737
recent_5_podiums                 3.145226
previous_podium                  3.145226
previous_points                  3.145226
recent_5_points                  3.145226
constructor_recent_5_podiums     0.774489
constructor_recent_5_points      0.774489
grid                             0.000000
dtype: float64

In [88]:
qualifying_by_year = (
    completed_results
    .groupby("year")["qualifying_position"]
    .apply(lambda x: x.notna().sum())
)

print(qualifying_by_year.tail(20))

year
2007    374
2008    368
2009    340
2010    456
2011    452
2012    476
2013    418
2014    405
2015    374
2016    457
2017    398
2018    420
2019    418
2020    340
2021    439
2022    440
2023    440
2024    479
2025    478
2026    261
Name: qualifying_position, dtype: int64

In [89]:
print(
    completed_results[
        completed_results["qualifying_position"].notna()
    ]["year"].min()
)

print(
    completed_results[
        completed_results["qualifying_position"].notna()
    ]["year"].max()
)

1994
2026

In [90]:
qualifying_years = (
    completed_results[
        completed_results["qualifying_position"].notna()
    ]
    .groupby("year")
    .size()
)

print(qualifying_years.head(20))

year
1994    392
1995    418
1996    148
1997    220
1998    153
1999     65
2000     88
2001     22
2002     42
2003    320
2004    360
2005    376
2006    396
2007    374
2008    368
2009    340
2010    456
2011    452
2012    476
2013    418
dtype: int64

In [91]:
completed_results["qualifying_missing"] = (
    completed_results["qualifying_position"].isna().astype(int)
)

print(
    completed_results
    .groupby("qualifying_missing")["podium"]
    .mean()
)

qualifying_missing
0    0.141547
1    0.117647
Name: podium, dtype: float64

In [92]:
feature_columns = [
    "grid",
    "qualifying_position",
    "qualifying_missing",
    "previous_finish_num",
    "previous_podium",
    "previous_points",
    "recent_5_podiums",
    "recent_5_points",
    "constructor_recent_5_podiums",
    "constructor_recent_5_points",
]

print("Number of features:", len(feature_columns))

for feature in feature_columns:
    print("-", feature)

Number of features: 10
- grid
- qualifying_position
- qualifying_missing
- previous_finish_num
- previous_podium
- previous_points
- recent_5_podiums
- recent_5_points
- constructor_recent_5_podiums
- constructor_recent_5_points

In [94]:
print(
    completed_results[feature_columns]
    .isin([float("inf"), float("-inf")])
    .sum()
)

grid                            0
qualifying_position             0
qualifying_missing              0
previous_finish_num             0
previous_podium                 0
previous_points                 0
recent_5_podiums                0
recent_5_points                 0
constructor_recent_5_podiums    0
constructor_recent_5_points     0
dtype: int64

In [96]:
print(
    completed_results[feature_columns].dtypes
)

grid                             object
qualifying_position             float64
qualifying_missing                int64
previous_finish_num             float64
previous_podium                 float64
previous_points                 float64
recent_5_podiums                float64
recent_5_points                 float64
constructor_recent_5_podiums    float64
constructor_recent_5_points     float64
dtype: object

In [97]:
print(completed_results["grid"].unique()[:20])

['3' '11' '13' '9' '8' '1' '21' '10' '5' '4' '6' '14' '18' '19' '20' '16'
 '17' '2' '15' '7']

In [98]:
print(
    completed_results["grid"]
    .value_counts()
    .tail(10)
)

grid
26    248
27     46
28     30
29     25
\N     20
30     19
31     18
32     17
33     13
34      1
Name: count, dtype: int64

In [99]:
completed_results["grid"] = pd.to_numeric(
    completed_results["grid"],
    errors="coerce"
)

print(completed_results["grid"].dtype)
print("Grid missing:", completed_results["grid"].isna().sum())

float64
Grid missing: 20

In [100]:
print(
    completed_results[feature_columns].isna().sum()
)

grid                               20
qualifying_position             16269
qualifying_missing                  0
previous_finish_num             11306
previous_podium                   865
previous_points                   865
recent_5_podiums                  865
recent_5_points                   865
constructor_recent_5_podiums      213
constructor_recent_5_points       213
dtype: int64

In [101]:
print(
    completed_results.loc[
        completed_results["grid"].isna(),
        ["year", "raceId", "driverId", "qualifying_position", "podium"]
    ]
)

       year  raceId  driverId  qualifying_position  podium
27198  2025    1167         1                 18.0       0
27199  2025    1167         4                  8.0       0
27200  2025    1167       807                 11.0       0
27201  2025    1167       830                  3.0       1
27202  2025    1167       832                  7.0       1
27203  2025    1167       839                 17.0       0
27204  2025    1167       840                 19.0       0
27205  2025    1167       842                  9.0       0
27206  2025    1167       844                 10.0       0
27207  2025    1167       846                  2.0       0
27208  2025    1167       847                  4.0       0
27209  2025    1167       848                 15.0       0
27210  2025    1167       852                 16.0       0
27211  2025    1167       857                  1.0       1
27212  2025    1167       859                 12.0       0
27213  2025    1167       860                 13.0       0
27214  2025    1167       861                 20.0       0
27215  2025    1167       863                  5.0       0
27216  2025    1167       864                 14.0       0
27217  2025    1167       865                  6.0       0

In [102]:
print(
    results.loc[
        results["raceId"] == 1167,
        ["driverId", "grid", "position"]
    ]
)

       driverId grid position
27198       830   \N        1
27199       857   \N        2
27200       832   \N        3
27201       846   \N        4
27202       863   \N        5
27203       847   \N        6
27204         4   \N        7
27205       844   \N        8
27206       859   \N        9
27207       852   \N       10
27208       848   \N       11
27209         1   \N       12
27210       864   \N       13
27211       861   \N       14
27212       839   \N       15
27213       842   \N       16
27214       840   \N       17
27215       865   \N       18
27216       860   \N       19
27217       807   \N       20

In [103]:
print(
    completed_results.loc[
        completed_results["grid"].isna(),
        "qualifying_position"
    ].isna().sum()
)

0

In [104]:
completed_results.loc[
    completed_results["grid"].isna(),
    "grid"
] = completed_results.loc[
    completed_results["grid"].isna(),
    "qualifying_position"
]

print("Grid missing:", completed_results["grid"].isna().sum())

Grid missing: 0

In [ ]:
previous_finish_missing_by_year = (
    completed_results[
        completed_results["previous_finish_num"].isna()
    ]
    .groupby("year")
    .size()
)

print(previous_finish_missing_by_year.head(20))

year
1950    121
1951     91
1952    135
1953    138
1954    117
1955     97
1956    106
1957    100
1958    129
1959    110
1960    121
1961    112
1962    120
1963    141
1964     93
1965     82
1966    101
1967    114
1968    137
1969     87
dtype: int64

In [106]:
first_race_check = (
    completed_results
    .groupby("driverId")["date"]
    .transform("min")
)

print(
    (
        completed_results["previous_finish_num"].isna()
        & (completed_results["date"] == first_race_check)
    ).sum()
)

869

In [107]:
missing_previous_finish = completed_results[
    completed_results["previous_finish_num"].isna()
]

print(
    "Missing previous finish:",
    len(missing_previous_finish)
)

print(
    "Drivers with missing previous finish:",
    missing_previous_finish["driverId"].nunique()
)

Missing previous finish: 11306
Drivers with missing previous finish: 865

In [108]:
missing_prev = completed_results[
    completed_results["previous_finish_num"].isna()
]

driver_first_date = (
    completed_results
    .groupby("driverId")["date"]
    .transform("min")
)

first_race_missing = (
    missing_prev["date"].values
    == driver_first_date[missing_prev.index].values
)

print("Missing previous finish rows:", len(missing_prev))
print("First-race missing rows:", first_race_missing.sum())
print(
    "Missing rows after driver's first race:",
    (~first_race_missing).sum()
)

Missing previous finish rows: 11306
First-race missing rows: 869
Missing rows after driver's first race: 10437

In [109]:
print(
    completed_results[
        (completed_results["driverId"] == 579)
    ][
        ["driverId", "date", "raceId", "position", "previous_finish_num"]
    ].head(15)
)

     driverId        date  raceId position  previous_finish_num
0         579  1950-05-13     833       \N                  NaN
26        579  1950-05-21     834        1                  NaN
80        579  1950-06-04     836       \N                  1.0
97        579  1950-06-18     837        1                  NaN
112       579  1950-07-02     838        1                  1.0
132       579  1950-09-03     839       \N                  1.0
133       579  1950-09-03     839       \N                  NaN
163       579  1951-05-27     825        1                  NaN
216       579  1951-06-17     827        9                  1.0
231       579  1951-07-01     828       11                  9.0
232       579  1951-07-01     828        1                 11.0
255       579  1951-07-14     829        2                  1.0
276       579  1951-07-29     830        2                  2.0
298       579  1951-09-16     831       \N                  2.0
321       579  1951-10-28     832        1                  NaN

In [110]:
duplicates = completed_results.duplicated(
    subset=["driverId", "raceId"],
    keep=False
)

print("Duplicate driver-race rows:", duplicates.sum())

Duplicate driver-race rows: 176

In [111]:
print(
    completed_results.loc[
        duplicates,
        ["driverId", "raceId", "date", "position", "positionOrder", "podium"]
    ].head(30)
)

     driverId  raceId        date position  positionOrder  podium
48        529     835  1950-05-30       \N             31       0
49        529     835  1950-05-30        5              5       0
115       627     838  1950-07-02       \N             12       0
116       627     838  1950-07-02        6              6       0
132       579     839  1950-09-03       \N             15       0
133       579     839  1950-09-03       \N             13       0
140       647     839  1950-09-03       \N             17       0
141       647     839  1950-09-03        2              2       1
231       579     828  1951-07-01       11             11       0
232       579     828  1951-07-01        1              1       1
240       647     828  1951-07-01        2              2       1
241       647     828  1951-07-01       \N             18       0
252       786     828  1951-07-01        1              1       1
253       786     828  1951-07-01       11             11       0
307       642     831  1951-09-16       \N             16       0
308       642     831  1951-09-16        3              3       1
348       642     817  1952-05-18       \N             15       0
349       642     817  1952-05-18       \N             10       0
417       501     820  1952-07-06       \N             19       0
418       501     820  1952-07-06       \N             15       0
517       759     823  1952-08-17       \N             17       0
518       759     823  1952-08-17        9              9       0
572       509     809  1953-05-30        7              7       0
573       509     809  1953-05-30       15             15       0
574       512     809  1953-05-30       \N             32       0
575       512     809  1953-05-30       \N             19       0
577       518     809  1953-05-30       \N             24       0
578       518     809  1953-05-30        3              3       1
579       520     809  1953-05-30       \N             28       0
580       520     809  1953-05-30        9              9       0

In [112]:
duplicate_check = completed_results.loc[
    duplicates,
    ["driverId", "raceId", "constructorId"]
]

print(
    duplicate_check
    .groupby(["driverId", "raceId"])["constructorId"]
    .nunique()
    .value_counts()
)

constructorId
1    69
2    15
3     1
Name: count, dtype: int64

In [113]:
duplicate_groups = (
    completed_results
    .groupby(["driverId", "raceId"])
    .size()
)

print(
    "Duplicate driver-race groups:",
    (duplicate_groups > 1).sum()
)

print(
    "Largest records for one driver-race:",
    duplicate_groups.max()
)

Duplicate driver-race groups: 85
Largest records for one driver-race: 3

In [114]:
print(
    completed_results.loc[
        duplicates,
        [
            "driverId",
            "raceId",
            "constructorId",
            "position",
            "positionOrder",
            "podium"
        ]
    ].head(20)
)

     driverId  raceId  constructorId position  positionOrder  podium
48        529     835            150       \N             31       0
49        529     835            113        5              5       0
115       627     838            154       \N             12       0
116       627     838            154        6              6       0
132       579     839             51       \N             15       0
133       579     839             51       \N             13       0
140       647     839              6       \N             17       0
141       647     839              6        2              2       1
231       579     828             51       11             11       0
232       579     828             51        1              1       1
240       647     828              6        2              2       1
241       647     828              6       \N             18       0
252       786     828             51        1              1       1
253       786     828             51       11             11       0
307       642     831             51       \N             16       0
308       642     831             51        3              3       1
348       642     817              6       \N             15       0
349       642     817              6       \N             10       0
417       501     820            105       \N             19       0
418       501     820            105       \N             15       0

In [115]:
duplicate_podium_rows = completed_results.loc[
    duplicates, "podium"
]

print("Duplicate rows:", len(duplicate_podium_rows))
print("Duplicate podium rows:", duplicate_podium_rows.sum())

Duplicate rows: 176
Duplicate podium rows: 24

In [116]:
duplicate_podium_counts = (
    completed_results.loc[duplicates]
    .groupby(["driverId", "raceId"])["podium"]
    .sum()
)

print(
    "Groups with multiple podium records:",
    (duplicate_podium_counts > 1).sum()
)

Groups with multiple podium records: 2

In [117]:
multi_podium_groups = duplicate_podium_counts[
    duplicate_podium_counts > 1
]

print(multi_podium_groups)

driverId  raceId
427       792       2
642       792       2
Name: podium, dtype: int64

In [118]:
for (driver_id, race_id) in multi_podium_groups.index:
    print(
        completed_results[
            (completed_results["driverId"] == driver_id) &
            (completed_results["raceId"] == race_id)
        ][
            [
                "driverId",
                "raceId",
                "constructorId",
                "position",
                "positionOrder",
                "podium"
            ]
        ]
    )
    print("-" * 50)

      driverId  raceId  constructorId position  positionOrder  podium
1030       427     792              6       \N             11       0
1031       427     792              6        2              2       1
1032       427     792              6        3              3       1
--------------------------------------------------
      driverId  raceId  constructorId position  positionOrder  podium
1054       642     792              6        3              3       1
1055       642     792              6        2              2       1
--------------------------------------------------

In [119]:
print("Total rows:", len(completed_results))

print(
    "Rows in duplicate driver-race groups:",
    duplicates.sum()
)

print(
    "Percentage affected:",
    round(duplicates.sum() / len(completed_results) * 100, 2),
    "%"
)

Total rows: 27502
Rows in duplicate driver-race groups: 176
Percentage affected: 0.64 %

In [120]:
print(completed_results[feature_columns].dtypes)

grid                            float64
qualifying_position             float64
qualifying_missing                int64
previous_finish_num             float64
previous_podium                 float64
previous_points                 float64
recent_5_podiums                float64
recent_5_points                 float64
constructor_recent_5_podiums    float64
constructor_recent_5_points     float64
dtype: object

In [121]:
print(
    "Non-numeric features:",
    completed_results[feature_columns]
    .select_dtypes(exclude="number")
    .columns.tolist()
)

Non-numeric features: []

In [122]:
print(completed_results["podium"].value_counts())

podium
0    23998
1     3504
Name: count, dtype: int64

In [124]:
print(completed_results["podium"].isna().sum())

0

In [126]:


X = completed_results[feature_columns].copy()
y = completed_results["podium"].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (27502, 10)
y shape: (27502,)

In [127]:
print(X.columns.tolist())

['grid', 'qualifying_position', 'qualifying_missing', 'previous_finish_num', 'previous_podium', 'previous_points', 'recent_5_podiums', 'recent_5_points', 'constructor_recent_5_podiums', 'constructor_recent_5_points']

In [128]:
print(
    completed_results["year"].min(),
    "to",
    completed_results["year"].max()
)

1950 to 2026

In [129]:
train_data = completed_results[
    completed_results["year"] < 2024
].copy()

test_data = completed_results[
    completed_results["year"] >= 2024
].copy()

print("Training rows:", len(train_data))
print("Testing rows:", len(test_data))

print(
    "Training years:",
    train_data["year"].min(),
    "to",
    train_data["year"].max()
)

print(
    "Testing years:",
    test_data["year"].min(),
    "to",
    test_data["year"].max()
)

Training rows: 26280
Testing rows: 1222
Training years: 1950 to 2023
Testing years: 2024 to 2026

In [130]:
X_train = train_data[feature_columns].copy()
y_train = train_data["podium"].copy()

X_test = test_data[feature_columns].copy()
y_test = test_data["podium"].copy()

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (26280, 10)
y_train: (26280,)
X_test: (1222, 10)
y_test: (1222,)

In [131]:
print("Training target:")
print(y_train.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

Training target:
podium
0    22956
1     3324
Name: count, dtype: int64

Testing target:
podium
0    1042
1     180
Name: count, dtype: int64

In [132]:
print("Training missing values:")
print(X_train.isna().sum())

print("\nTesting missing values:")
print(X_test.isna().sum())

Training missing values:
grid                                0
qualifying_position             16265
qualifying_missing                  0
previous_finish_num             11251
previous_podium                   858
previous_points                   858
recent_5_podiums                  858
recent_5_points                   858
constructor_recent_5_podiums      210
constructor_recent_5_points       210
dtype: int64

Testing missing values:
grid                             0
qualifying_position              4
qualifying_missing               0
previous_finish_num             55
previous_podium                  7
previous_points                  7
recent_5_podiums                 7
recent_5_points                  7
constructor_recent_5_podiums     3
constructor_recent_5_points      3
dtype: int64

In [133]:
print(
    completed_results.loc[
        completed_results["qualifying_position"].isna(),
        "qualifying_missing"
    ].value_counts()
)

qualifying_missing
1    16269
Name: count, dtype: int64

In [134]:
print(
    completed_results[
        [
            "previous_finish_num",
            "previous_podium",
            "previous_points"
        ]
    ].isna().sum()
)

previous_finish_num    11306
previous_podium          865
previous_points          865
dtype: int64

In [135]:
print(
    completed_results[
        [
            "previous_finish_num",
            "previous_podium",
            "previous_points"
        ]
    ].isna()
    .all(axis=1)
    .sum()
)

865

In [136]:
print(
    completed_results[
        ["recent_5_podiums", "recent_5_points"]
    ].isna().sum()
)

print(
    "Both missing:",
    completed_results[
        ["recent_5_podiums", "recent_5_points"]
    ].isna().all(axis=1).sum()
)

recent_5_podiums    865
recent_5_points     865
dtype: int64
Both missing: 865

In [137]:
print(
    completed_results[
        [
            "constructor_recent_5_podiums",
            "constructor_recent_5_points"
        ]
    ].isna().sum()
)

print(
    "Both missing:",
    completed_results[
        [
            "constructor_recent_5_podiums",
            "constructor_recent_5_points"
        ]
    ].isna().all(axis=1).sum()
)

constructor_recent_5_podiums    213
constructor_recent_5_points     213
dtype: int64
Both missing: 213

In [138]:
no_history = completed_results[
    completed_results["previous_podium"].isna() &
    completed_results["previous_points"].isna() &
    completed_results["recent_5_podiums"].isna() &
    completed_results["recent_5_points"].isna()
]

print("No-history rows:", len(no_history))

first_race = (
    completed_results
    .groupby("driverId")["date"]
    .transform("min")
)

print(
    "No-history rows that are first race:",
    (
        no_history["date"].values ==
        first_race[no_history.index].values
    ).sum()
)

No-history rows: 865
No-history rows that are first race: 865

In [139]:
constructor_first_date = (
    completed_results
    .groupby("constructorId")["date"]
    .transform("min")
)

no_constructor_history = completed_results[
    completed_results["constructor_recent_5_podiums"].isna() &
    completed_results["constructor_recent_5_points"].isna()
]

print("No constructor-history rows:", len(no_constructor_history))

print(
    "Constructor first-race rows:",
    (
        no_constructor_history["date"].values ==
        constructor_first_date[no_constructor_history.index].values
    ).sum()
)

No constructor-history rows: 213
Constructor first-race rows: 213

In [140]:
history_zero_features = [
    "previous_podium",
    "previous_points",
    "recent_5_podiums",
    "recent_5_points",
    "constructor_recent_5_podiums",
    "constructor_recent_5_points"
]

completed_results[history_zero_features] = (
    completed_results[history_zero_features].fillna(0)
)

print(
    completed_results[history_zero_features].isna().sum()
)

previous_podium                 0
previous_points                 0
recent_5_podiums                0
recent_5_points                 0
constructor_recent_5_podiums    0
constructor_recent_5_points     0
dtype: int64

In [141]:
print(
    completed_results["previous_finish_num"].describe()
)

count    16196.000000
mean         8.072734
std          4.892903
min          1.000000
25%          4.000000
50%          8.000000
75%         12.000000
max         24.000000
Name: previous_finish_num, dtype: float64

In [142]:
completed_results["previous_finish_num"] = (
    completed_results["previous_finish_num"].fillna(8)
)

print(
    "Missing previous_finish_num:",
    completed_results["previous_finish_num"].isna().sum()
)

Missing previous_finish_num: 0

In [143]:
print(
    completed_results["qualifying_position"].describe()
)

count    11233.000000
mean        11.168343
std          6.241580
min          1.000000
25%          6.000000
50%         11.000000
75%         16.000000
max         28.000000
Name: qualifying_position, dtype: float64

In [144]:



completed_results["qualifying_position"] = (
    completed_results["qualifying_position"].fillna(11)
)

print(
    "Missing qualifying_position:",
    completed_results["qualifying_position"].isna().sum()
)

Missing qualifying_position: 0

In [145]:

print(
    completed_results[feature_columns].isna().sum()
)

grid                            0
qualifying_position             0
qualifying_missing              0
previous_finish_num             0
previous_podium                 0
previous_points                 0
recent_5_podiums                0
recent_5_points                 0
constructor_recent_5_podiums    0
constructor_recent_5_points     0
dtype: int64

In [146]:
X_train = completed_results.loc[
    completed_results["year"] < 2024,
    feature_columns
].copy()

y_train = completed_results.loc[
    completed_results["year"] < 2024,
    "podium"
].copy()

X_test = completed_results.loc[
    completed_results["year"] >= 2024,
    feature_columns
].copy()

y_test = completed_results.loc[
    completed_results["year"] >= 2024,
    "podium"
].copy()

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (26280, 10)
y_train: (26280,)
X_test: (1222, 10)
y_test: (1222,)

In [147]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Model training completed!")

Model training completed!

In [148]:

y_pred = model.predict(X_test)

print("Predictions completed!")
print("Predicted podiums:", y_pred.sum())

Predictions completed!
Predicted podiums: 160

In [149]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy : 0.9034369885433715
Precision: 0.69375
Recall   : 0.6166666666666667
F1 Score : 0.6529411764705882

Confusion Matrix:
[[993  49]
 [ 69 111]]

In [150]:
feature_importance = pd.Series(
    model.feature_importances_,
    index=feature_columns
).sort_values(ascending=False)

print(feature_importance)

grid                            0.294849
recent_5_points                 0.170256
constructor_recent_5_points     0.150705
recent_5_podiums                0.142375
constructor_recent_5_podiums    0.082509
previous_finish_num             0.069309
qualifying_position             0.041104
previous_points                 0.034934
qualifying_missing              0.009204
previous_podium                 0.004754
dtype: float64

In [151]:
from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test)[:, 1]

auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", auc)

ROC-AUC: 0.9347568777991042